# Decoration config
source = ~/.config/hypr/themes/arcane/decoration.conf

# Animations config
source = ~/.config/hypr/themes/arcane/animations.conf

# Main monitors config
source = ~/.config/hypr/config/monitors.conf

# Programs config
source = ~/.config/hypr/config/programs.conf

# Input devices
source = ~/.config/hypr/config/input.conf

# Misc configs
source = ~/.config/hypr/config/misc.conf

# Keybindings
source = ~/.config/hypr/config/keybindings.conf

# Window Rules
source = ~/.config/hypr/config/windowrules.conf

# Autostart apps
source = ~/.config/hypr/config/autostart.conf
