#      _   _   _ _____ ___  ____ _____  _    ____ _____ 
#     / \ | | | |_   _/ _ \/ ___|_   _|/ \  |  _ \_   _|
#    / _ \| | | | | || | | \___ \ | | / _ \ | |_) || |  
#   / ___ \ |_| | | || |_| |___) || |/ ___ \|  _ < | |  
#  /_/   \_\___/  |_| \___/|____/ |_/_/   \_\_| \_\|_|  
#                                                       

source = ~/.config/hypr/config/programs.conf

exec-once = uwsm app -- swww-daemon
exec-once = uwsm app -- swaync
exec-once = uwsm app -- $terminal
exec-once = uwsm app -- $browser
exec-once = uwsm app -- waybar
exec-once = uwsm app -- spotify
exec-once = hyprctl dispatch workspace 1
exec-once = hyprctl dispatch workspace 1
exec-once = playerctld
