
#  __        _____ _   _ ____   _____        __  ____  _   _ _     _____ ____  
#  \ \      / /_ _| \ | |  _ \ / _ \ \      / / |  _ \| | | | |   | ____/ ___| 
#   \ \ /\ / / | ||  \| | | | | | | \ \ /\ / /  | |_) | | | | |   |  _| \___ \ 
#    \ V  V /  | || |\  | |_| | |_| |\ V  V /   |  _ <| |_| | |___| |___ ___) |
#     \_/\_/  |___|_| \_|____/ \___/  \_/\_/    |_| \_\\___/|_____|_____|____/ 
#                                                                              


# 32 inch left monitor
windowrulev2 = workspace 3, class:^(firefox)$

# vertical monitor
windowrulev2 = workspace 2, class:^(Code)$
windowrulev2 = workspace 5, class:^(discord)$
windowrulev2 = workspace 5, class:^(WebCord)$

# main monitor
windowrulev2 = workspace 10, class:^(Spotify|spotify)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:
