##################################################
### _   _                  _                 _ ###
###| | | |_   _ _ __  _ __| | __ _ _ __   __| |###
###| |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |###
###|  _  | |_| | |_) | |  | | (_| | | | | (_| |###
###|_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|###
###       |___/|_|                             ###
##################################################


# Decoration config
source = ~/.config/hypr/themes/spiderverse/decoration.conf

# Animations config
source = ~/.config/hypr/config/animations.conf

# Main monitors config
source = ~/.config/hypr/config/monitors.conf

# Autostart apps
source = ~/.config/hypr/config/autostart.conf

# Programs config
source = ~/.config/hypr/config/programs.conf

# Misc configs
source = ~/.config/hypr/config/misc.conf

# Input devices
source = ~/.config/hypr/config/input.conf

# Keybindings
source = ~/.config/hypr/config/keybindings.conf

# Window rules
source = ~/.config/hypr/config/windowrules.conf

# Env Variables
source = ~/.config/hypr/config/env.conf
